# Generated by Django 5.1.1 on 2024-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_ut', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rape', models.IntegerField()),
                ('kidnapping_and_abduction', models.IntegerField()),
                ('dowry_deaths', models.IntegerField()),
                ('assault_on_women', models.IntegerField()),
                ('insult_to_modesty', models.IntegerField()),
                ('cruelty_by_husband', models.IntegerField()),
                ('importation_of_girls', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
